//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inkton.Nester {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inkton.Nester.Text", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API/CLI.
        /// </summary>
        internal static string api {
            get {
                return ResourceManager.GetString("api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        internal static string app {
            get {
                return ResourceManager.GetString("app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archival.
        /// </summary>
        internal static string archive {
            get {
                return ResourceManager.GetString("archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string auto_register {
            get {
                return ResourceManager.GetString("auto_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Renew.
        /// </summary>
        internal static string auto_renew {
            get {
                return ResourceManager.GetString("auto_renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string backup {
            get {
                return ResourceManager.GetString("backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth.
        /// </summary>
        internal static string bandwidth_gb_month {
            get {
                return ResourceManager.GetString("bandwidth_gb_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        internal static string batch {
            get {
                return ResourceManager.GetString("batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string configuration {
            get {
                return ResourceManager.GetString("configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured.
        /// </summary>
        internal static string configured {
            get {
                return ResourceManager.GetString("configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        internal static string cpu {
            get {
                return ResourceManager.GetString("cpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Kit.
        /// </summary>
        internal static string development_kit {
            get {
                return ResourceManager.GetString("development_kit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string domain {
            get {
                return ResourceManager.GetString("domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string DomainNormal {
            get {
                return ResourceManager.GetString("DomainNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        internal static string DomainPrimary {
            get {
                return ResourceManager.GetString("DomainPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSD.
        /// </summary>
        internal static string drive_ssd_gb {
            get {
                return ResourceManager.GetString("drive_ssd_gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade/Downgrade Plan.
        /// </summary>
        internal static string flexible {
            get {
                return ResourceManager.GetString("flexible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed.
        /// </summary>
        internal static string managed {
            get {
                return ResourceManager.GetString("managed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        internal static string memory_mb {
            get {
                return ResourceManager.GetString("memory_mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Metrics.
        /// </summary>
        internal static string metrics {
            get {
                return ResourceManager.GetString("metrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop/Mobile Console.
        /// </summary>
        internal static string mobile_desktop_console {
            get {
                return ResourceManager.GetString("mobile_desktop_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        internal static string monitor {
            get {
                return ResourceManager.GetString("monitor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The domain alias list is incorrectly formed or a domain name invalid.
        /// </summary>
        internal static string NEST_RESULT_HTTP_400
        {
            get
            {
                return ResourceManager.GetString("NEST_RESULT_HTTP_400", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The domain alias list is incorrectly formed or a domain name invalid.
        /// </summary>
        internal static string NEST_RESULT_HTTP_401
        {
            get
            {
                return ResourceManager.GetString("NEST_RESULT_HTTP_401", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The domain alias list is incorrectly formed or a domain name invalid.
        /// </summary>
        internal static string NEST_RESULT_HTTP_403
        {
            get
            {
                return ResourceManager.GetString("NEST_RESULT_HTTP_403", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The domain alias list is incorrectly formed or a domain name invalid.
        /// </summary>
        internal static string NEST_RESULT_HTTP_ERROR
        {
            get
            {
                return ResourceManager.GetString("NEST_RESULT_HTTP_ERROR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The domain alias list is incorrectly formed or a domain name invalid.
        /// </summary>
        internal static string NEST_RESULT_DOMAIN_ALIAS_MALFORMED {
            get {
                return ResourceManager.GetString("NEST_RESULT_DOMAIN_ALIAS_MALFORMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default domain cannot be changed.
        /// </summary>
        internal static string NEST_RESULT_DOMAIN_DEFAULT {
            get {
                return ResourceManager.GetString("NEST_RESULT_DOMAIN_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation failed.
        /// </summary>
        internal static string NEST_RESULT_ERROR {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a payment method to resume.
        /// </summary>
        internal static string NEST_RESULT_ERROR_ADD_PAYMENT_METHOD {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_ADD_PAYMENT_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy the app before this operation.
        /// </summary>
        internal static string NEST_RESULT_ERROR_APP_ASSIGN_TREE {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_ASSIGN_TREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app already deployed.
        /// </summary>
        internal static string NEST_RESULT_ERROR_APP_DEPLOYED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_DEPLOYED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app already exist.
        /// </summary>
        internal static string NEST_RESULT_ERROR_APP_EXISTS {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The worker needs an app handler first.
        /// </summary>
        internal static string NEST_RESULT_ERROR_APP_HANDLER_NEEDED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_HANDLER_NEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app should be deployed first.
        /// </summary>
        internal static string NEST_RESULT_ERROR_APP_NDEPLOYED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_NDEPLOYED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application not found.
        /// </summary>
        internal static string NEST_RESULT_ERROR_APP_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_NFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is not ready.
        /// </summary>
        internal static string NEST_RESULT_ERROR_APP_NREADY {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_NREADY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app cannot be updated whilst in this state.
        /// </summary>
        internal static string NEST_RESULT_ERROR_APP_NUPDATES {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_NUPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service cannot be turnd off.
        /// </summary>
        internal static string NEST_RESULT_ERROR_APP_SERVICE_ALWAYS_ON {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_SERVICE_ALWAYS_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cancel - this is an essential service.
        /// </summary>
        internal static string NEST_RESULT_ERROR_APP_SERVICE_ESSENTIAL {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_SERVICE_ESSENTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application service tier already exists.
        /// </summary>
        internal static string NEST_RESULT_ERROR_APP_SERVICE_FTIER_EXIST {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_SERVICE_FTIER_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application service tier already exists.
        /// </summary>
        internal static string NEST_RESULT_ERROR_APP_SERVICE_TIER_EXIST {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_SERVICE_TIER_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a dedicated application service tier.
        /// </summary>
        internal static string NEST_RESULT_ERROR_APP_SERVICE_TIER_NDEDICATED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_SERVICE_TIER_NDEDICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application service subscription not found.
        /// </summary>
        internal static string NEST_RESULT_ERROR_APP_SERVICE_TIER_NEEDED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_SERVICE_TIER_NEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application service tier not found.
        /// </summary>
        internal static string NEST_RESULT_ERROR_APP_SERVICE_TIER_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_SERVICE_TIER_NFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a shared application service tier.
        /// </summary>
        internal static string NEST_RESULT_ERROR_APP_SERVICE_TIER_NSHARED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_SERVICE_TIER_NSHARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag does not exist.
        /// </summary>
        internal static string NEST_RESULT_ERROR_APP_TAG_EXIST {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_TAG_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of users allowed for the plan exceeded.
        /// </summary>
        internal static string NEST_RESULT_ERROR_CONTACT_EXCEEDED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_CONTACT_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact not found.
        /// </summary>
        internal static string NEST_RESULT_ERROR_CONTACT_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_CONTACT_NFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deployment already exist.
        /// </summary>
        internal static string NEST_RESULT_ERROR_DEPLOYMENT_EXIST {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_DEPLOYMENT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment not found.
        /// </summary>
        internal static string NEST_RESULT_ERROR_DEPLOYMENT_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_DEPLOYMENT_NFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The doployment ID is always zero..
        /// </summary>
        internal static string NEST_RESULT_ERROR_DEPLOYMENT_WRONGID {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_DEPLOYMENT_WRONGID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one domain certificate can be assigned.
        /// </summary>
        internal static string NEST_RESULT_ERROR_DOMAIN_CERT_ASSIGNED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_DOMAIN_CERT_ASSIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain certificate not found.
        /// </summary>
        internal static string NEST_RESULT_ERROR_DOMAIN_CERT_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_DOMAIN_CERT_NFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain not found.
        /// </summary>
        internal static string NEST_RESULT_ERROR_DOMAIN_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_DOMAIN_NFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain is unregistered.
        /// </summary>
        internal static string NEST_RESULT_ERROR_DOMAIN_UNREGISTERED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_DOMAIN_UNREGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured - please contact support.
        /// </summary>
        internal static string NEST_RESULT_ERROR_FATAL {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_FATAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the input - there are errors.
        /// </summary>
        internal static string NEST_RESULT_ERROR_FIELDS {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application service subcription is missing.
        /// </summary>
        internal static string NEST_RESULT_ERROR_FOREST_APP_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_FOREST_APP_NFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The forest not found.
        /// </summary>
        internal static string NEST_RESULT_ERROR_FOREST_INVALID {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_FOREST_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest not found.
        /// </summary>
        internal static string NEST_RESULT_ERROR_FOREST_NOT_FOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_FOREST_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot install a server here.
        /// </summary>
        internal static string NEST_RESULT_ERROR_FOREST_NOT_PLANTABLE {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_FOREST_NOT_PLANTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service cannot be added.
        /// </summary>
        internal static string NEST_RESULT_ERROR_INVALID_SERVICE_LEVEL {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_INVALID_SERVICE_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation not found.
        /// </summary>
        internal static string NEST_RESULT_ERROR_INVITATION_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_INVITATION_NFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to login.
        /// </summary>
        internal static string NEST_RESULT_ERROR_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized to complete this operation.
        /// </summary>
        internal static string NEST_RESULT_ERROR_NAUTH {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_NAUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nest handler already exist.
        /// </summary>
        internal static string NEST_RESULT_ERROR_NEST_HANDLER_EXIST {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_NEST_HANDLER_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nest not found.
        /// </summary>
        internal static string NEST_RESULT_ERROR_NEST_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_NEST_NFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nest host platform not found.
        /// </summary>
        internal static string NEST_RESULT_ERROR_NPLATFORM_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_NPLATFORM_NFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment server busy, please try again in a few minutes.
        /// </summary>
        internal static string NEST_RESULT_ERROR_PAYMENT_BUSY {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_PAYMENT_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment declined.
        /// </summary>
        internal static string NEST_RESULT_ERROR_PAYMENT_DECLINED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_PAYMENT_DECLINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission already exist.
        /// </summary>
        internal static string NEST_RESULT_ERROR_PERM_FOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_PERM_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission not found.
        /// </summary>
        internal static string NEST_RESULT_ERROR_PERM_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_PERM_NFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method not found.
        /// </summary>
        internal static string NEST_RESULT_ERROR_PMETHOD_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_PMETHOD_NFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application service not found.
        /// </summary>
        internal static string NEST_RESULT_ERROR_SERVICE_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_SERVICE_NFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service type already exists.
        /// </summary>
        internal static string NEST_RESULT_ERROR_SERVICE_TYPE_EXISTS {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_SERVICE_TYPE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application service subscription invalid.
        /// </summary>
        internal static string NEST_RESULT_ERROR_SUBSCRIPTION_INVALID {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_SUBSCRIPTION_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application service subscription not found.
        /// </summary>
        internal static string NEST_RESULT_ERROR_SUBSCRIPTION_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_SUBSCRIPTION_NFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription cannot be changed in current app state.
        /// </summary>
        internal static string NEST_RESULT_ERROR_SUBSCRIPTION_STATE {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_SUBSCRIPTION_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree not found.
        /// </summary>
        internal static string NEST_RESULT_ERROR_TREE_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_TREE_NFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not authorizied.
        /// </summary>
        internal static string NEST_RESULT_ERROR_USER_NAUTH {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_USER_NAUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string NEST_RESULT_ERROR_USER_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_USER_NFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A handler nest not found - add a handler nest.
        /// </summary>
        internal static string NEST_RESULT_NEST_HANDLER_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_NEST_HANDLER_NFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was a success.
        /// </summary>
        internal static string NEST_RESULT_SUCCESS {
            get {
                return ResourceManager.GetString("NEST_RESULT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation completed with warnings.
        /// </summary>
        internal static string NEST_RESULT_WARNING {
            get {
                return ResourceManager.GetString("NEST_RESULT_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is being updated.
        /// </summary>
        internal static string NEST_RESULT_WARNING_UPDATING {
            get {
                return ResourceManager.GetString("NEST_RESULT_WARNING_UPDATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalable.
        /// </summary>
        internal static string scalable {
            get {
                return ResourceManager.GetString("scalable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string storage {
            get {
                return ResourceManager.GetString("storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Management.
        /// </summary>
        internal static string team_management {
            get {
                return ResourceManager.GetString("team_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier-1.
        /// </summary>
        internal static string tier_1 {
            get {
                return ResourceManager.GetString("tier_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier-2.
        /// </summary>
        internal static string tier_2 {
            get {
                return ResourceManager.GetString("tier_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier-3.
        /// </summary>
        internal static string tier_3 {
            get {
                return ResourceManager.GetString("tier_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier-4.
        /// </summary>
        internal static string tier_4 {
            get {
                return ResourceManager.GetString("tier_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier-5.
        /// </summary>
        internal static string tier_5 {
            get {
                return ResourceManager.GetString("tier_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier-6.
        /// </summary>
        internal static string tier_6 {
            get {
                return ResourceManager.GetString("tier_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier-7.
        /// </summary>
        internal static string tier_7 {
            get {
                return ResourceManager.GetString("tier_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier-8.
        /// </summary>
        internal static string tier_8 {
            get {
                return ResourceManager.GetString("tier_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        internal static string track {
            get {
                return ResourceManager.GetString("track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
    }
}
